name: github action demo pipeline 
on:
    push:
        branches:
            - main

jobs:
    extract-job:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout code 
              uses: actions/checkout@v2 

            - name: Set Up Python
              uses: actions/setup-python@v4 
              with:
                python-version: '3.10'

            - name: Intall Dependencies 
              run: pip install -r requirements.txt 

            - name: Run Extract.py
              run: python extract.py

    transform-job:
        runs-on: ubuntu-latest 
        needs: extract-job 
        steps:
            - name: Checkout code 
              uses: actions/checkout@v2

            - name: Run Transform.py
              run: python transform.py

    load-job:
        runs-on: ubuntu-latest 
        needs: transform-job 
        steps:
            - name: Checkout code 
              uses: actions/checkout@v2 

            - name: Run Load.py
              run: python load.py